Add API functionality to 'Enable'/'Disable' buttons
The functionality of the 'Enable' and 'Disable'
buttons need to be implemented to use the IPA
commands through the RPC wrapper. This will
allow to remove existing users from the IPA
server.

The modification of the user status is managed
by the `DisableEnableUsers` modal, that has been
adapted to consume the commands using the
`useBatchMutCommandMutation` endpoint.

The following IPA commands are being used:
- `user_disable`
- `user_enable`

Depending on the current user status
(`nsaccountlock`), the modal messages and
operations will be adapted. For example, if
a user is enabled and we wanted to disable it,
the modal title, content text, and the action
buttons inside the `DisableEnableUsers` modal
will be set to perform the 'disable' operation
(and the other way around).

Potential errors when executing the commands
mentioned above are contained inside the API
response, not in a separate variable. E.g.:

```ts
// Expected: 'error' and 'result' are
//   independent
export interface BatchRPCResponse {
  error: string;
  id: string;
  principal: string;
  version: string;
  result: {
    count: number;
    results: {
      result: Record<string, unknown>; // General object type
      truncated: boolean;
      summary: string;
    };
  };
}

// Obtained: Two 'error'variables, one
//   contained inside 'result'.
export interface BatchRPCResponse {
  error: string;
  id: string;
  principal: string;
  version: string;
  result: {
    count: number;
    results: {
      error: {<different-structure>}
      result: Record<string, unknown>;
      truncated: boolean;
      summary: string;
    };
  };
}
```

In order to catch and show this error via
`ErrorModal` modal, a new data structure has
been defined to prepare the error data. Then,
it has been set as a custom `FetchBaseQueryError`,
and sent it to the `handleAPIError` function.

```ts
if (result) {
  if ("error" in result.results[0]) {
    // Error inside 'result'.
    // 1.- Prepare data as 'ErrorData'
    const errorData = {
      code: result.results[0].error_code,
      name: result.results[0].error_name,
      error: result.results[0].error,
    } as ErrorData;

    // 2.- Prepare the error data as
    //    as 'FetchBaseQueryError'
    const error = {
      status: "CUSTOM_ERROR",
      data: errorData,
    } as FetchBaseQueryError;

    // 3.- Handle error
    handleAPIError(error);
  } else {
    // No errors received here
  }
} else if (error) {
  // Handle errors as usual
}
```

```ts
// 'ErrorData' data structure
export interface ErrorData {
  code: string;
  name: string;
  error: string;
}
```

Signed-off-by: Carla Martinez <carlmart@redhat.com>